server.port: 9000



spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 734791831463-lh6tqtbq4dll7h8joj57ng2ugporm9e1.apps.googleusercontent.com
            client-secret: wJxQ9UwDT9o58fjRoI9kcL0n

